import { type GeneratorConfig } from "./gen-icons";

const config: GeneratorConfig = {
  outDir: "./src/components/icons/",
  entries: [
    {
      name: "lucide",
      refer: "https://lucide.dev/icons/",
      prefix: "Lu",
      baseUrl: "https://cdn.jsdelivr.net/npm/lucide-static@latest/icons",
      coloring: "stroke",
      icons: ["plus"],
    },
    {
      name: "logos",
      prefix: "Lo",
      refer: "https://svgporn.com/",
      baseUrl: "https://raw.githubusercontent.com/gilbarbara/logos/main/logos/",
      coloring: "keep",
      icons: ["apple", "google-icon", "stripe"],
    },
    {
      name: "heroicons",
      prefix: "He",
      refer: "https://heroicons.com/",
      baseUrl: "https://cdn.jsdelivr.net/npm/heroicons@latest/24/outline/",
      coloring: "stroke",
      icons: [
        "arrow-left",
        "arrow-long-right",
        "arrow-path",
        "check-circle",
        "check",
        "key",
        "trash",
        "x-mark",
      ],
    },
    {
      name: "monoicons",
      prefix: "Mo",
      refer: "https://icons.mono.company/",
      baseUrl:
        "https://raw.githubusercontent.com/mono-company/mono-icons/master/svg/",
      coloring: "keep",
      replaceColor: "#0D0D0D",
      icons: ["user", "settings", "notification", "log-out"],
    },
    {
      name: "tabler",
      prefix: "Ta",
      refer: "https://tabler-icons.io/",
      baseUrl: "https://tabler-icons.io/static/tabler-icons/icons/",
      coloring: "stroke",
      icons: [
        "access-point",
        "arrows-transfer-down",
        "arrows-transfer-up",
        "check",
        "circle-plus",
        "device-mobile-check",
        "file-text",
        "file-type-csv",
        "file-type-pdf",
        "file-type-sql",
        "file-type-xml",
        "file-type-zip",
        "file-unknown",
        "hand-click",
        "help-circle",
        "key-off",
        "key",
        "movie",
        "music",
        "photo",
        "player-pause",
        "player-play",
        "send",
        "square-plus",
        "square-rounded-plus",
        "wifi-2",
        "x",
      ],
    },
    // {
    //   name: 'carbon',
    //   prefix: 'Ca',
    //   refer: 'https://carbondesignsystem.com/guidelines/icons/library/',
    //   baseUrl: 'https://cdn.jsdelivr.net/npm/@carbon/icons@latest/svg/24/',
    //   icons: [
    //   ],
    // },
  ],
};
export default config;
